fnNIDAQ='H:\Data\myRun2_g0_t0.nidq.bin';
fpNIDAQ=fopen(fnNIDAQ);
datNIDAQ=fread(fpNIDAQ,[2,Inf],'*int16');
fclose(fpNIDAQ);
figure
plot(datNIDAQ(1,:));
%%
fnAP='H:\Data\myRun2_g0_imec0\myRun2_g0_t0.imec0.ap.bin';
fpAP=fopen(fnAP);
%datAP=fread(fpAP,[385,Inf],'*int16');
fseek(fpAP,384*2,0);
datAP=fread(fpAP,[1,Inf],'*int16',2*384);
fclose(fpAP);
%%
figure
plot(datAP);

%%
figure
t_AP=linspace(0,1,size(datAP,2));
t_NIDAQ=linspace(0,1,size(datNIDAQ,2));
plot(t_NIDAQ,datNIDAQ(1,:)>5000);
hold on
plot(t_AP,datAP>50,'--');
%%
%%
nidaqD=interp1(t_NIDAQ,double(datNIDAQ(1,:)>5000),t_AP);
figure
plot(nidaqD-double(datAP>50))
